Fix/cf proxy www ssl error
itwzhp/infrastruktura pull request #187
Opened 2022-12-28 21:45 UTC by kowalczyk-p

2022-12-28 21:52 UTC, kowalczyk-p commented
Wrzuciłem zmianę kasującą nie działające CNAMEy, co myślicie?

2022-12-29 07:41 UTC, karol-gro requested changes

2022-12-29 07:41 UTC, karol-gro commented on domains/functions/delegation.js
>  function Delegation_A_WithCfProxy(domain, record, suffix) {
sufix jest niepotrzebny teraz

2022-12-29 07:41 UTC, karol-gro commented on domains/zhp.pl.d/wydzial-it.js
> +    Delegation_A_WithCfProxy('komunikaty.gk', '51.75.54.175', 'zhp.pl'), // BUG CF SSL ERROR
wiesz, co to za strona?

2022-12-29 08:48 UTC, szczot3k commented on domains/zhp.pl.d/wydzial-it.js
> +    Delegation_A_WithCfProxy('komunikaty.gk', '51.75.54.175', 'zhp.pl'), // BUG CF SSL ERROR
komunikaty.gk.zhp.pl to pozostałość, teraz kieruje (specjalnie) na sharepointa gk

2022-12-29 08:56 UTC, karol-gro commented on domains/zhp.pl.d/wydzial-it.js
> +    Delegation_A_WithCfProxy('komunikaty.gk', '51.75.54.175', 'zhp.pl'), // BUG CF SSL ERROR
to skoro nie działa to możemy chyba wywalić? Ew. przerzucić do redirectów jeśli tego potrzebujemy

2022-12-29 08:57 UTC, szczot3k commented on domains/zhp.pl.d/wydzial-it.js
> +    Delegation_A_WithCfProxy('komunikaty.gk', '51.75.54.175', 'zhp.pl'), // BUG CF SSL ERROR
I mean, https://komunikaty.gk.zhp.pl działają. Nie działa z prefixem www.

2022-12-29 08:58 UTC, karol-gro commented on domains/zhp.pl.d/wydzial-it.js
> +    Delegation_A_WithCfProxy('komunikaty.gk', '51.75.54.175', 'zhp.pl'), // BUG CF SSL ERROR
No u mnie nie bardzo: 
![image](https://user-images.githubusercontent.com/865361/209927957-88ed1a23-4f90-4b3e-b88e-78c4b67463dc.png)

2022-12-29 08:58 UTC, karol-gro commented on domains/zhp.pl.d/wydzial-it.js
> +    Delegation_A_WithCfProxy('komunikaty.gk', '51.75.54.175', 'zhp.pl'), // BUG CF SSL ERROR
I, jak rozumiem, to jest ten `BUG CF SSL ERROR`

2022-12-29 10:17 UTC, kowalczyk-p commented on domains/zhp.pl.d/wydzial-it.js
> +    Delegation_A_WithCfProxy('komunikaty.gk', '51.75.54.175', 'zhp.pl'), // BUG CF SSL ERROR
To czy działa czy nie zależy od tego, czy przeglądarka zacznie od http czy https - jak zwykłe http to pójdzie, jak zacznie z https to nie pójdzie. Certyfikat w CF obejmuje tylko jeden poziom nad zhp.pl, gdybyśmy zrobili komunikaty-gk.zhp.pl to by działało ;)

Natomiast patrząc na ruch w analityce CF to wchodzą tam boty, jakiś czytnik RSS i dwa wejścia dzisiaj z wczoraj. Ta strona chyba długo była martwa i nie jest już używana.

2022-12-29 10:23 UTC, kowalczyk-p commented on domains/functions/delegation.js
>  function Delegation_A_WithCfProxy(domain, record, suffix) {
Wywaliłem

2022-12-29 10:32 UTC, kowalczyk-p commented on domains/zhp.pl.d/wydzial-it.js
> +    Delegation_A_WithCfProxy('komunikaty.gk', '51.75.54.175', 'zhp.pl'), // BUG CF SSL ERROR
Ja bym proponował usunąć komunikaty.gk.zhp.pl i archiwum.fsj.zhp.pl - obie nie działają, ruchu nie widać, nikt problemów nie zgłasza.

2022-12-29 11:34 UTC, karol-gro commented on domains/zhp.pl.d/wydzial-it.js
> +    Delegation_A_WithCfProxy('komunikaty.gk', '51.75.54.175', 'zhp.pl'), // BUG CF SSL ERROR
Archiwum FSJ miało stać dopóki strona FŚJ nie będzie doprowadzona do porządku, teraz to jakoś wygląda ale nadal mają jakieś lorem ipsum tu i ówdzie na podstronach.  Ale chyba można wyłączyć

2022-12-29 12:55 UTC, kowalczyk-p commented on domains/zhp.pl.d/wydzial-it.js
> +    Delegation_A_WithCfProxy('komunikaty.gk', '51.75.54.175', 'zhp.pl'), // BUG CF SSL ERROR
Usunąłem domeny, najwyżej się doda ponownie bez proxy CF jak będzie potrzeba.

2022-12-29 13:25 UTC, karol-gro approved these changes

2022-12-29 14:19 UTC, merged