Change zachodniopomorska records NS to A + Ms365 + redirects
itwzhp/infrastruktura pull request #196
Opened 2023-02-01 10:47 UTC by norberto5

2023-02-01 13:41 UTC, karol-gro approved these changes

2023-02-02 13:08 UTC, szczot3k requested changes

2023-02-02 13:08 UTC, szczot3k commented on domains/redirects/redirectFiles/zhp.pl.json
> +    // Zachodniopomorska
do zmiany, wywala się redirect engine przez to

2023-02-02 13:31 UTC, norberto5 commented on domains/redirects/redirectFiles/zhp.pl.json
> +    // Zachodniopomorska
Poprawione

2023-02-02 13:32 UTC, szczot3k commented
@karol-gro, redirect engine się wywala przez błędne credsy do AZ. O ile się nie pali, to poczekałbym na naprawę problemu (CC: @kovansky) przed mergem.

2023-02-02 13:35 UTC, norberto5 commented
> @karol-gro, redirect engine się wywala przez błędne credsy do AZ. O ile się nie pali, to poczekałbym na naprawę problemu (CC: @kovansky) przed mergem.

A to nie wynika z tego, że to na forku? ;) GitHub actions na forku nie mają dostępu do sekretów z głównego repo

2023-02-02 13:37 UTC, szczot3k approved these changes
yolo, myślałem, że skoro jesteś memberem tego repo, to wrzuciłeś bezpośrednio w brancha u nas xd

2023-02-02 13:37 UTC, merged