Przeniesienie DNS-ów Hufca Mokotów
itwzhp/infrastruktura pull request #197
Opened 2023-02-01 19:04 UTC by xartuu

**Cześć 👋**

Podsyłam PR z rekordami DNS Hufca Mokotów. Na chwilę obecną wstrzymujemy się jeszcze z przeniesieniem strefy DNS - czekamy na zgodę.

Mamy mały bałagan w DNS 😅, m.in. poczta Arsenału kierowana jest jeszcze do Google Workspace i mamy dziwne rekordy Microsoftu *o ile się nie mylę* dotyczące Skype (nie wiem czy potrzebne). Mamy kilka stronek stworzonych w Google Sites i wiemy, że ktoś trzymał pliki na Dysku Google w `@mokotow.zhp.pl` i/albo `@arsenal.zhp.pl`, więc temat Google niestety nie jest jeszcze u nas zamknięty i szukamy administratora, który ma tam dostęp, żeby odzyskać dane.

Zdecydowanie po przeniesieniu strefy DNS chcielibyśmy zabezpieczyć strony i Wordpressy za pomocą firewalla od Cloudflare, wymusić przekierowanie na https na poziomie CF oraz jesteśmy zainteresowani podpięciem monitoringu pod nasze stronki (tylko ta kwesta do konsultacji wewnątrz - kto ma otrzymywać powiadomienia o dostępności strony).

Planujemy też oczyścić część rekordów z niedziałających stron, więc na bieżąco będziemy aktualizowali DNS.

2023-02-01 19:20 UTC, karol-gro requested changes

2023-02-01 19:20 UTC, karol-gro commented on domains/zhp.pl.d/stoleczna.js
> +    Delegation_A('2021.arsenal', '91.227.122.220', 'zhp.pl'),
Większość nie działa, chyba można przy okazji wyrzucić

2023-02-01 19:20 UTC, karol-gro commented on domains/zhp.pl.d/stoleczna.js
> +    CNAME('autodiscover.mokotow', 'autodiscover.outlook.com.'),
Wyrzuć to wszystko i użyj ```Ms365_Subdomain('mokotow', 'zhp.pl'),```

2023-02-01 19:20 UTC, karol-gro commented on domains/zhp.pl.d/stoleczna.js
> +    MX('arsenal', 60, 'ASPMX5.GOOGLEMAIL.COM.'),
Mamy testy wykrywające MX-y poza MS365 i one się wysypały 

Czy ktoś tam jeszcze tę pocztę odbiera? Być może trzeba by najpierw się tych googli pozbyć

2023-02-01 20:48 UTC, xartuu commented on domains/zhp.pl.d/stoleczna.js
> +    Delegation_A('2021.arsenal', '91.227.122.220', 'zhp.pl'),
Na pewno mamy w planach zrobić "*archiwum*" arsenałów. Jeszcze nie rozmawialiśmy w jakiej formie miałoby ono być - ja to widzę na zasadzie subdomeny `archium.arsenal.zhp.pl` i tam zakładki z informacjami i oprawą wizualną danego aresnału. Jak przypuszczam po DNS, z każdą edycją arsenału poprzednia strona była wrzucana do subdomeny i tylko główna strona była aktualizowana, stąd też starsze odsłony nie działają.

2023-02-01 20:53 UTC, xartuu commented on domains/zhp.pl.d/stoleczna.js
> +    CNAME('autodiscover.mokotow', 'autodiscover.outlook.com.'),
Check ✔️

2023-02-01 20:56 UTC, xartuu commented on domains/zhp.pl.d/stoleczna.js
> +    MX('arsenal', 60, 'ASPMX5.GOOGLEMAIL.COM.'),
Jedynie wiem, że ktoś trzyma pliki w Dysku Google `@mokotow.zhp.pl`, pewnie też w `@arsenal.zhp.pl`, ale raczej wątpię, żeby ktoś odbierał tam pocztę, chociaż z drugiej strony nie mam pewności.

2023-02-01 21:59 UTC, karol-gro commented on domains/zhp.pl.d/stoleczna.js
> +    Delegation_A('2021.arsenal', '91.227.122.220', 'zhp.pl'),
No to czeka Was trochę pracy, bo to nie tak łatwo odpalić stronę sprzed 10 lat, jeśli np. Nie działa ze wspieraną wersją bazy czy php.
Być może wystarczy bazować na webarchive

2023-02-07 18:12 UTC, xartuu commented
Uprzątnąłem trochę stron - część nie działała lub rezygnujemy z nich. Strony Arsenałowe planujemy przenieść do archiwum w jednym miejscu. Deadline na spokojnie po Arsenale.

2023-02-07 18:15 UTC, xartuu commented on domains/zhp.pl.d/stoleczna.js
> +    Delegation_A('2021.arsenal', '91.227.122.220', 'zhp.pl'),
Wyrzuciłem wszystkie 🫡
Pół żartem pół serio, tak jak mówisz większość nie działa, a na reszcie było mało treści. Zostawiam je jeszcze na hostingu, żeby przez lokalne DNS mieć do nich dostęp, ale będziemy powoli robili archiwum Arsenałowe.

2023-02-07 18:17 UTC, xartuu commented on domains/zhp.pl.d/stoleczna.js
> +    MX('arsenal', 60, 'ASPMX5.GOOGLEMAIL.COM.'),
Zastanawiam się, czy nie utrudni nam to ewentualnego dostępu do Dysku i Gmaila, jak znajdziemy administratora i dobijemy się do tego.

2023-02-07 18:22 UTC, szczot3k commented on domains/zhp.pl.d/stoleczna.js
> +    MX('arsenal', 60, 'ASPMX5.GOOGLEMAIL.COM.'),
Mokotów i Arsenal powinny jak najszybciej zniknąć z Gsuite. Jak będzie trzeba, to mogę pomóc z procedurą odzyskiwania administratora.

2023-02-07 18:29 UTC, xartuu commented on domains/zhp.pl.d/stoleczna.js
> +    MX('arsenal', 60, 'ASPMX5.GOOGLEMAIL.COM.'),
Obecnie kontaktujemy się z potencjalnymi administratorami, którzy mieliby dostęp, żeby odzyskać dane, które mogą być dla nas dalej przydatne. Dla mnie to też jest priorytetowa sprawa i od razu dam update, jak posuniemy się do przodu.

2023-02-11 14:03 UTC, xartuu commented on domains/zhp.pl.d/stoleczna.js
> +    MX('arsenal', 60, 'ASPMX5.GOOGLEMAIL.COM.'),
Daję obiecany update, skontaktowaliśmy się z administratorem G Suite i odzyskaliśmy dostęp do mokotowskiego G Suite. Niestety nie mamy już wykupionej licencji i nie możemy dostać się do danych na dysku. Próbowałem pobrać dane dzięki Google Takeout, ale przy pobieraniu spotykam się z komunikatem "Sensitive action blocked" (przez niedawne zmiany na koncie). Macie jakieś rady, jak wyciągnąć stamtąd dane?

2023-02-13 08:43 UTC, karol-gro commented on domains/zhp.pl.d/stoleczna.js
> +    MX('arsenal', 60, 'ASPMX5.GOOGLEMAIL.COM.'),
Dwa pomysły:
1. kupić jedną licencję na miesiąc (chyba ta za 5.20 €) i poprzerzucać do kont, żeby na nie wejść
2. czekać, logować się z jednego kompa (jednej przeglądarki per konto), podpiąć MFA i wierzyć, że kiedyś Google ci zaufa

2023-03-21 22:18 UTC, xartuu commented on domains/zhp.pl.d/stoleczna.js
> +    MX('arsenal', 60, 'ASPMX5.GOOGLEMAIL.COM.'),
Upewniliśmy się w 100% i już wiemy, że nie odzyskamy danych z tych kont. Kontaktowaliśmy się nawet z samym Google. Dane zostały usunięte wraz z wygaśnięciem naszej licencji ngo w G Suite, ale w panelu administracyjnym nie odświeżyły się informacje - w raportach, aż do czasu zakupu nowej licencji (w celu dostępu do Dysku Google), widniała informacja o zajętym miejscu, 60gb w usłudze Drive. Pogodziliśmy się z utratą tych danych, odzyskaliśmy za to część zdjęć z Google Photos. W przyszłym tygodniu zamykamy konta zarówno w arsenałowym i mokotowskim G Suite.

2023-03-21 22:23 UTC, xartuu commented
Przeprowadzamy aktualnie zmianę hostingu. Wcześniej korzystaliśmy z unixstorma, teraz przenosimy się do dhostingu, który obsługuje oprogramowanie litespeed, żeby nasze stronki śmigały.

Dosłownie na dniach wygasa nam poprzedni hosting, a więc zaraz pojawi się tutaj więcej commitów ode mnie. Wszystko postaramy się jak najszybciej dopiąć, żeby przenieść strefę DNS bez żadnych przerw w dostępności stron.

2023-03-22 08:40 UTC, karol-gro requested changes
Wygląda już dużo lepiej i przechodzi testy
Zwracam tylko uwagę na kilka wpisów, które kierują na niedziałające strony. Wiele w z nich nie tyle jest pusta, co pluje jakimiś błędami ze starego oprogramowania

I tak są obecnie bezwartościowe, a wystawianie ich niestety może być zagrożeniem dla wszystkich stron na tym koncie w hostingu (w zależności od konfiguracji), bo czasem błąd w jednej aplikacji pozwala dodać trochę kodu do wszystkich stronek ;) 

Dlatego proponuję je na razie wyrzucić, ew. zakomentować i przywracać jak będzie ktoś chętny na odświeżenie lub postawienie na nowo tych stron

2023-03-22 08:40 UTC, karol-gro commented on domains/zhp.pl.d/stoleczna.js
> +    Delegation_A('154.mokotow', '91.227.122.220', 'zhp.pl'),
Nie działa ;) Potrzebne?

2023-03-22 08:40 UTC, karol-gro commented on domains/zhp.pl.d/stoleczna.js
> +    Delegation_A('69wdhiz.mokotow', '91.227.122.220', 'zhp.pl'),
nie działa ;)

2023-03-22 08:40 UTC, karol-gro commented on domains/zhp.pl.d/stoleczna.js
> +    Delegation_A('dok.mokotow', '91.227.122.220', 'zhp.pl'),
nie działa ;)

2023-03-22 08:40 UTC, karol-gro commented on domains/zhp.pl.d/stoleczna.js
> +    Delegation_A('e-rajd.mokotow', '91.227.122.220', 'zhp.pl'),
nie działa

2023-03-22 08:40 UTC, karol-gro commented on domains/zhp.pl.d/stoleczna.js
> +    Delegation_A('gra.mokotow', '91.227.122.220', 'zhp.pl'),
nie działa

2023-03-22 08:40 UTC, karol-gro commented on domains/zhp.pl.d/stoleczna.js
> +    Delegation_A('oboz.mokotow', '91.227.122.220', 'zhp.pl'),
nie działa

2023-03-22 08:40 UTC, karol-gro commented on domains/zhp.pl.d/stoleczna.js
> +    Delegation_A('wedrownicy.mokotow', '91.227.122.220', 'zhp.pl'),
nie działa

2023-03-22 08:40 UTC, karol-gro commented on domains/zhp.pl.d/stoleczna.js
> +    CNAME('1procent.mokotow', 'ghs.google.com.'),
nie działa

2023-03-22 08:40 UTC, karol-gro commented on domains/zhp.pl.d/stoleczna.js
> +    CNAME('ksh.mokotow', 'ghs.google.com.'),
nie działą

2023-03-22 08:40 UTC, karol-gro commented on domains/zhp.pl.d/stoleczna.js
> +    CNAME('przewodnikowski.mokotow', 'ghs.google.com.'),
nie działa

2023-03-22 08:40 UTC, karol-gro commented
Ale to już Wasza decyzja, co z tymi stronkami zrobić

2023-03-22 16:49 UTC, xartuu commented on domains/zhp.pl.d/stoleczna.js
> +    Delegation_A('e-rajd.mokotow', '91.227.122.220', 'zhp.pl'),
Ta strona wysypała się podczas migracji. Twierdzi, że moduł PHP jest niedostępny mimo, że jest aktywny na hostingu. Próbuję znaleźć przyczynę i docelowo będzie działała.

2023-03-22 17:13 UTC, xartuu commented
Parę stronek zostało na poprzednim hostingu i tam pluje błędami. Zrobiłem backup starego hostingu i wrzuciłem go na nowy. Jeżeli znajdzie się zainteresowana osoba pomogę przywrócić stronki. Jak przeniesiemy strefę DNS, to usuwamy stamtąd pliki i bazy danych.
Ostatni commit przedstawia strony na nowym hostingu. Jedna się wywaliła, bo uznała, że nie ma dostępnego modułu PHP (mimo, że jest dostępny). Wszystkie strony mają ograniczony `open_basedir`, więc żadna strona nie powinna mieć wpływu na drugą (przykładowo, żeby wstrzyknąć kod). Bazy danych są zabezpieczone firewallem i są dostępne tylko wewnątrz hostingu. Odrobiłem swoją pracę domową 😄

Jeszcze dam potwierdzenie, ale jesteśmy gotowi dzisiaj na przeniesienie strefy DNS.

2023-03-22 21:37 UTC, karol-gro approved these changes

2023-03-22 21:37 UTC, merged