Redirect aktywacja
itwzhp/infrastruktura pull request #198
Opened 2023-02-02 18:46 UTC by kowalczyk-p

2023-02-02 18:55 UTC, kowalczyk-p commented
@karol-gro @szczot3k Coś nie działa z redirectami na zhp.net.pl?

2023-02-02 19:07 UTC, karol-gro commented on domains/redirects/redirectFiles/zhp.net.pl.json
> +    "aktywacja": { "target": "https://pomoc.zhp.pl/display/PUB", "method": 302 }
ej, są dwie aktywacje teraz...

2023-02-02 19:08 UTC, karol-gro requested changes
popraw dwie aktywacje

2023-02-03 09:55 UTC, kowalczyk-p commented
Ups...

2023-02-06 11:52 UTC, merged