Update gdanska.js
itwzhp/infrastruktura pull request #203
Opened 2023-02-20 22:58 UTC by ROBI22122001

Malbork - zmiana rekordu i dodanie TXT do weryfikacji SSL

2023-02-20 23:01 UTC, ROBI22122001 commented
Na razie stoi tam pusta strona od WordPressa, w tym tygodniu przeniesiemy pełną stronę :)

2023-02-21 07:54 UTC, karol-gro requested changes

2023-02-21 07:54 UTC, karol-gro commented on domains/zhp.pl.d/gdanska.js
> +    TXT('ovhcontrol','T396GI3dwKTqVUxXmdX9cg'), //weryfikacja do SSL - Malbork
ten wpis raczej powinien być w subdomenie malborka, a nie w głównej domenie ZHP. Nie macie uprawnień do występowania w imieniu ZHP

2023-02-21 09:28 UTC, ROBI22122001 commented on domains/zhp.pl.d/gdanska.js
> +    TXT('ovhcontrol','T396GI3dwKTqVUxXmdX9cg'), //weryfikacja do SSL - Malbork
Od OVH mam akurat taką informację
![image](https://user-images.githubusercontent.com/68379198/220304290-7520de46-648f-455a-b4d6-9e7f9ba579da.png)
Możemy na razie to pominąć, niech zostanie sam rekord A

2023-02-21 11:57 UTC, karol-gro commented on domains/zhp.pl.d/gdanska.js
> +    TXT('ovhcontrol','T396GI3dwKTqVUxXmdX9cg'), //weryfikacja do SSL - Malbork
No tak, ale Ty nie masz udowadniać im, że domena zhp.pl jest pod Twoją kontrolą, bo nie jest. Możesz zweryfikować malbork.zhp.pl

2023-02-21 11:58 UTC, ROBI22122001 commented on domains/zhp.pl.d/gdanska.js
> +    TXT('ovhcontrol','T396GI3dwKTqVUxXmdX9cg'), //weryfikacja do SSL - Malbork
Dobra, to już to ogarniemy sami, poproszę tylko o zmianę rekordu A 😄

2023-02-21 12:07 UTC, karol-gro approved these changes

2023-02-21 12:08 UTC, merged