Feature/stoleczna
itwzhp/infrastruktura pull request #33
Opened 2021-04-22 21:05 UTC by jaj02k

Stołeczna - wyczyszczenie nadmiarowych rekordów

2021-04-22 21:45 UTC, szczot3k requested changes
Zweryfikowałem, czy wszystkie z hufców którym usuwamy MX w naszej strefie mają je w naszej (ale nie weryfikowałem TXT).
1. milanowek.zhp.pl ma MX tylko u nas EDIT: ma u nas i na webd, choć na webd jest niepoprawny
2. piastow.zhp.pl ma MX u nas i na zenboxie, ale te na zenboxie wskazuja na mx{1-3}.zenbox.pl
3. warszawazoliborz.zhp.pl ma MX tylko u nas


Oprócz tego:
1. Widzę rekordy MX dla subdomen *.nowydwormaz.zhp.pl - czy to jest potrzebne? Te rekordy nie wskazują na MS365.
2. J/w - zawiszacy.otwock.zhp.pl
3. Widzę w spf dla stoleczna.zhp.pl "ip4:185.255.40.28" - wskazujący na sieć atthosta, czy to potrzebne?

Nie gwarantuje, że sprawdziłem wszystkie delegacja NS, czy będą działać po zmergowaniu tego PR.

2021-04-22 22:18 UTC, jaj02k commented
> Zweryfikowałem, czy wszystkie z hufców którym usuwamy MX w naszej strefie mają je w naszej (ale nie weryfikowałem TXT).
> 
> 1. milanowek.zhp.pl ma MX tylko u nas
> 2. piastow.zhp.pl ma MX u nas i na zenboxie, ale te na zenboxie wskazuja na mx{1-3}.zenbox.pl
> 3. warszawazoliborz.zhp.pl ma MX tylko u nas

To nawiązując też do rozmowy na teams to temat do wyjaśnienia.
W założeniach NS powinien w całości przekazać zarządzanie. Pytanie czy faktycznie tego nie robi, czy tylko te opcje odpytywania dostają odpowiedź z wszystkich wpisów które mają niezależnie od tego czy mają faktyczne znaczenie dla działania danej usługi.

> Oprócz tego:
> 
> 1. Widzę rekordy MX dla subdomen *.nowydwormaz.zhp.pl - czy to jest potrzebne? Te rekordy nie wskazują na MS365.
> 2. J/w - zawiszacy.otwock.zhp.pl

Tych dwóch nie ruszałem na razie (zmieniłem tylko kolejność, żeby trochę uporządkować)
To są domeny, których nie mamy na chorągwianym hostingu, więc zmiany wymagają kontaktu z hufcami.

> 3. Widzę w spf dla stoleczna.zhp.pl "ip4:185.255.40.28" - wskazujący na sieć atthosta, czy to potrzebne?

Tak było ustawione na wcześniejszym hostingu, więc przeniosłem aktualizując adres.
Jak nie jest konieczne to usunę.

> Nie gwarantuje, że sprawdziłem wszystkie delegacja NS, czy będą działać po zmergowaniu tego PR.

Większość tego co usunąłem mam po swojej stronie na hostingu chorągwi, więc tego się nie obawiam.
Jedyne co to

2021-04-23 06:46 UTC, qj0n commented
Przy okazji można wywalić wszystkie sip, enterprise* itp ;)

2021-04-23 06:52 UTC, qj0n commented
BTW, @szczot3k miałem taki pomysł, żeby kiedyś dodać do CI test, czy nie ma wpisów kolidujących z NS. Bo DNScontrol na nie pozwala (jako glue recordy), ale w praktyce są u nas niechciane. Z tym, że przy okazji trzeba by wszystkie wywalić, więc na razie poczekamy z tym aż będzie trochę większy porządek z domenami

2021-04-23 09:54 UTC, qj0n commented on domains/zhp.pl.d/stoleczna.js
> +    // hufiec blonie (s)
Co oznacza ten `(s)`?

2021-04-23 09:54 UTC, qj0n commented on domains/zhp.pl.d/stoleczna.js
> +    // hufiec blonie (s)
Moja sugestia byłaby taka, żeby w komentarzach stosować _ładne_ formy, np `// Hufiec Błonie` i to `(s)` również rozpisać.

Z drugiej strony, jak sprzątniemy będziemy mieli 1-2 wpisy na hufiec, nie wiem, czy warto opisywać każdą linię, bo ten kod jest dość samoodokumentujący się (widać, że chodzi o delegację Błoni)

2021-04-23 09:54 UTC, qj0n commented on domains/zhp.pl.d/stoleczna.js
>      AAAA('ipv6.nowydwormazowiecki', '2a02:25a9:0:4893::1'),
Zastanawiam się, czy warto mieć wpisy IPv6 pod oddzielną subdomeną, tam raczej niewiele dają. Za to możemy pomyśleć o wpisie IPv6 na użytek głownej domeny, o ile serwer to przyjmie

2021-04-23 09:54 UTC, qj0n commented on domains/zhp.pl.d/stoleczna.js
>      CNAME('enterpriseenrollment.nowydwormazowiecki', 'enterpriseenrollment.manage.microsoft.com.'),
Z tych wszystkich wpisów można zostawić moim zdaniem:
- `Delegation_A` - wpis A dla głównej domeny i `www.`
- `Ms365_Subdomain` - konfiguracja Office
- IPv6 - na razie można zostawić AAAA, potem można by dodać wsparcie tego do `Delegation_A`

2021-04-23 09:54 UTC, qj0n commented on domains/zhp.pl.d/stoleczna.js
> +    CNAME('*.nowydwormaz', 'nowydwormaz.zhp.pl.'),
Jak sprzątniemy temat tego maila to można zrobić to zwykłym `Delegation_CNAME`

2021-04-23 09:54 UTC, qj0n commented on domains/zhp.pl.d/stoleczna.js
>      A('wakacje.nowydwormaz', '62.129.232.147'),
`Delegation_A` (tu i niżej w sumie)

2021-04-23 09:54 UTC, qj0n commented on domains/zhp.pl.d/stoleczna.js
>      Delegation_NS('piotrekbroda.otwock', ['ns3.clientnshosting.net.', 'ns4.clientnshosting.net.']),
Kilka z nich sprawdziłem i leżą. Cokolwiek z tego jeszcze stoi?

2021-04-24 13:12 UTC, jaj02k commented on domains/zhp.pl.d/stoleczna.js
> +    // hufiec blonie (s)
Jeśli chodzi o (s) to sobie tak skrótowo oznaczyłem, że to chorągwiany hosting.
Jeśli chodzi o komentarze to na teraz chciałem to podzielić, bo niektóre hufce mają mnóstwo rekordów (chyba mieli kogoś z hufca w zespole, że woleli tak zamiast zabrać wszystko do siebie). Jak się uda w miarę uporządkować i powyjaśniać to można będzie usunąć.

2021-04-24 13:14 UTC, jaj02k commented on domains/zhp.pl.d/stoleczna.js
>      AAAA('ipv6.nowydwormazowiecki', '2a02:25a9:0:4893::1'),
Trudno mi tu coś więcej powiedzieć, bo ten hufiec (i inne z tymi rekordami) ogarnia to we własnym zakresie, więc na ten moment nie mam wiedzy czy było im to potrzebne czy tak z rozpędu prosili o ustawienie.

2021-04-24 13:16 UTC, jaj02k commented on domains/zhp.pl.d/stoleczna.js
>      Delegation_NS('piotrekbroda.otwock', ['ns3.clientnshosting.net.', 'ns4.clientnshosting.net.']),
To jest do weryfikacji. Podejrzewam, że były ustawiane dawno temu, a że wszystko było ukryte w konfiguracji centralnie bez dostępu to nikt nad tym nie panował.

2021-04-24 14:59 UTC, qj0n commented
LGTM. Docelowo 2 duże rzeczy trzeba uprzątnąć, będziemy się nad nimi pochylać globalnie, ale pewnie możecie też wcześniej na to zwracać uwagę:

1. Wpisy NS nie powinny występować wraz z innymi wpisami
2. Maile powinny być tylko na Ms365

2021-04-24 14:59 UTC, qj0n approved these changes

2021-04-25 01:27 UTC, szczot3k reviewed
Powiem szczerze. Wolałbym, żeby przed mergem zniknęły z naszej strefy wpisy MS365 dla hufców którym delegujemy NSy i pojawiły się one w odpowiednich strefach. Naprawmy to jak najszybciej, ja "na dniach" postaram się przygotować listę duplikatów tego typu dla całego ZHP.

2021-04-25 01:28 UTC, szczot3k approved these changes

2021-04-25 16:14 UTC, merged