Chorągiew Śląska - swoje domeny
itwzhp/infrastruktura pull request #47
Opened 2021-05-06 11:26 UTC by puszkow

Wyjęcie domen Slaskiej do osobnego pliku

2021-05-06 11:43 UTC, karol-gro approved these changes

2021-05-06 11:43 UTC, karol-gro commented on domains/zhp.pl.d/slaska.js
> +    Delegation_NS('piekaryslaskie', ['fns1.42.pl.', 'fns2.42.pl.']),
Czy skoro oni używają 42.pl to czy są na hostingu chorągwi?

2021-05-06 11:43 UTC, karol-gro commented on domains/zhp.pl.d/slaska.js
> +    A('bazapajak', '91.211.221.203'),
Polecam użyć `Delegation_A` - obsłuży przy okazji www

2021-05-06 11:43 UTC, karol-gro commented on domains/zhp.pl.d/slaska.js
> +    Ms365_Subdomain('lubliniec','zhp.pl'),
Generalnie te wszystkie wpisy, które mają jednocześnie `Delegation_NS` jak i coś innego (zwykle `Ms365_Subdomain`) będzie trzeba sprzątnąć

2021-05-06 11:45 UTC, karol-gro requested changes

2021-05-06 11:45 UTC, karol-gro commented on domains/zhp.pl.zone.js
>      Delegation_NS('zyrardow', ['ns1.atthost.pl.', 'ns2.atthost.pl.']),
Tu na końcu linii masz przecinek, a po ostatnim nie powinno być przecinka - to blokuje zbudowanie

2021-05-06 11:56 UTC, puszkow commented on domains/zhp.pl.d/slaska.js
> +    Delegation_NS('piekaryslaskie', ['fns1.42.pl.', 'fns2.42.pl.']),
Oni są na hostingu chorągwi z poprawnym jako piekary.zhp.pl  
używali piekaryslaskie.zhp.pl - to bedzie w najbliższym czasie do usunięcia

2021-05-06 11:56 UTC, puszkow commented on domains/zhp.pl.d/slaska.js
> +    A('bazapajak', '91.211.221.203'),
Ok. zrobię.

2021-05-06 11:56 UTC, puszkow commented on domains/zhp.pl.d/slaska.js
> +    Ms365_Subdomain('lubliniec','zhp.pl'),
To jest to o czym rozmawialiśmy wczoraj - wiekszość na dhostingu - sam zasugerowałeś, żeby tamto pododawać ;)

2021-05-06 12:11 UTC, karol-gro commented on domains/zhp.pl.d/slaska.js
> +    Ms365_Subdomain('lubliniec','zhp.pl'),
Generalnie jeśli jest NS to nie powinno być nic innego. Bo jeśli mamy NS to znaczy, że tamten serwer jest odpowiedzialny za wszystkie wpisy (w tym Ms365). Z tym, że obecnie mamy dużo już takich błędów, więc zanim się to usunie trzeba przyjrzeć się, jak wygląda konfiguracja po stronie tamtego serwera. Ostatecznie trzeba doprowadzić do jednej z dwóch opcji:
1. Mamy Delegation_NS i wszystkie 5 wpisów (3xCNAME, TXT, MX) są po stronie tamtego serwera (np. dhosting)
2. Mamy Delegation_A oraz wpisujemy Ms365_Subdomain

HME doprowadziłem do opcji 2. Jeśli chcesz doprowadzić jakąś domenę do opcji 1 to najpierw upewnij się, że po stronie hostingu są dobre wpisy (na 95% brakuje tych wpisów DKIM, o których mówił Paweł), potem skasuje Ms365

2021-05-06 12:16 UTC, karol-gro commented on domains/zhp.pl.d/slaska.js
> +    Ms365_Subdomain('siemianowice','zhp.pl')
Tu brakuje przecinka

2021-05-06 20:20 UTC, karol-gro commented
Pozostaje jeszcze tylko jeden temat blokujący: czechowice-dziedzice. MS ma chyba jakiś problem z tym myślnikiem i jakoś inaczej generuje potrzebne domeny. Wydaje mi się, że lepiej będzie na razie zostawić takie wpisy jakie są dla MX ew. dodać brakujące niż zastępować funkcją Ms365, bo nie wiem, czy to nie zepsuje

2021-05-08 15:36 UTC, karol-gro commented
@puszkow Pozwoliłem sobie nanieść trochę zmian (merge, sprzątnąłem wcięcia i rozwiązałem problem z Czechowicami)

@szczot3k @kowalczyk-p @vasiliev123 - Tak żebyście wiedzieli: MS _dziwnie_ obsługuje domeny z myślnikiem. Normalnie my zastępujemy kropki myślnikami i wstawiamy jako część adresów MX oraz DKIM (np. `przysucha-zhp-pl.mail.protection.outlook.com.`). Problem w tym, że jeśli w adresie jest myślnik to MS usuwa myślnik, a następnie dodaje na końcu jakieś krzaki. Na oko wygląda to na kod hex ASCII znaku.

Jedyna taka domena w naszym Ms365 jak na razie to czechowice-dziedzice.zhp.pl i ich klucz to `czechowicedziedzice-zhp-pl02e` (02E to kod dla kropki). Ale dodałem dla testów inną domenę i MS też usunął myślnik, ale dodał 01c (w ASCII to _File Separator_).

Stąd dodałem opcję ustawienia tego klucza ręcznie. Domyślnie ustawia się po staremu. Na razie tylko Czechowice-Dziedzice mają myślnik w adresie, ale jakby było więcej myślników to trzeba uważać

2021-05-08 16:02 UTC, szczot3k approved these changes
LGTM

2021-05-08 16:23 UTC, karol-gro approved these changes

2021-05-08 16:23 UTC, merged