Create redirect engine (azure function)
itwzhp/infrastruktura pull request #53
Opened 2021-05-18 13:04 UTC by kovansky

Cała apka redirectowa, gotowa do pushowania na Azure Functions.
CI/CD zrobię na osobnym branchu i w osobnym PR.

2021-05-21 17:55 UTC, karol-gro requested changes

2021-05-21 17:55 UTC, karol-gro commented on domains/redirects/__tests__/redirectFiles.test.js
> +                              pass:    valid
Czy tu powinno być `pass: valid`? Chyba jakiś `fail` czy coś podobnego (nie znam frameworka, nie poprawię)

2021-05-21 17:55 UTC, karol-gro commented on domains/redirects/RedirectHttp/index.js
> +    });
Proponuję załadować te pliki poza obsługą funkcji - wtedy załadują się raz przy starcie aplikacji i nie będą opóźniać kolejnych requestów
https://stackoverflow.com/questions/48815835/azure-function-run-code-on-startup-for-node

2021-05-21 17:55 UTC, karol-gro commented on domains/redirects/RedirectHttp/index.js
> +        let redirect = addPathname(defaultURL, req);
W przypadku domyślnego redirecta proponuję nie doklejać ścieżki. Jak ktoś wchodzi na jakiś niedziałający, stary adres to raczej nie zadziała on po podmiane domeny na domyślne zhp.pl.

W ogóle pytanie, czy chcemy zachowywać path. Zwykle te redirecty wynikają z tego, że stara strona została wyłączona i jej treść jest np. na Sharepoincie lub zhp.pl. Wtedy jest nowa adresacja i nie ma to sensu.

Z drugiej strony, mogę sobie wyobrazić, że gdzieś serio taki redirect się przyda z zachowaniem końcówki. Ale to raczej jako opcja do włączenia w jsonie i nie ustawiane domyślnie

2021-05-21 19:33 UTC, kovansky commented on domains/redirects/__tests__/redirectFiles.test.js
> +                              pass:    valid
`valid` jest tutaj nazwą zmiennej — i tak przyjmuje `true` albo `false`, więc uznałem, że użyję zmiennej. Ale zmienię na true/false dla czytelności.

2021-05-21 20:12 UTC, karol-gro commented on domains/redirects/__tests__/redirectFiles.test.js
> +                              pass:    valid
aaa, już widzę. No to może być zmienna, ale wtedy bym ją nazwał `isValid`

2021-05-21 21:00 UTC, szczot3k commented on domains/redirects/RedirectHttp/index.js
> +        let redirect = addPathname(defaultURL, req);
+1 za opcją włączenia zachowywania `path`, ale nie by default. Większość naszych redirectów jest pathless.

2021-05-22 14:18 UTC, karol-gro commented on domains/redirects/RedirectHttp/index.js
> +        let redirect = addPathname(defaultURL, req);
OK, poprawiłem, ale testy pokazują, że nie działa. Dodawany był path, ale nie query.

Można to albo poprawić, albo wywalić całkowicie i zrobić, jak będzie potrzebne

2021-05-23 10:48 UTC, kovansky commented on domains/redirects/RedirectHttp/index.js
> +        let redirect = addPathname(defaultURL, req);
Zrobiłem, że dodaje też query. Kwestia dwóch linijek, a dzięki temu mamy to po prostu do włączenia w opcjach, a nie ma potrzeby potem dopisywać, gdyby jakoś gwałtownie było potrzebne.

2021-05-23 13:11 UTC, karol-gro commented on domains/redirects/RedirectHttp/index.js
> +        let redirect = addPathname(defaultURL, req);
No nie do końca dwóch linijek, bo dopisałem na to więcej testów i nie wszystkie przeszły, musiałem jeszcze trochę dofixować. Wygląda na to, że działa, ale nie wiem, czy tak, jak byśmy się spodziewali, jeśli będziemy tego potrzebować - np. jak targetUrl będzie sam mieć query to się wszystko pokopie. No ale dopóki pracujemy na urlu jak na stringu to zawsze będą takie przypadki

2021-05-23 13:11 UTC, karol-gro approved these changes

2021-05-23 13:12 UTC, karol-gro commented
OK, daję approve, potem możemy pocisnąć CI/CD

2021-05-28 16:33 UTC, karol-gro commented
@kovansky czy można merge'ować?

2021-05-28 17:04 UTC, kovansky commented
Tak — z tej części to wszystko na razie, CI/CD będzie na osobnym PR.

2021-05-28 17:41 UTC, merged