Create redirects CI/CD
itwzhp/infrastruktura pull request #60
Opened 2021-05-31 13:29 UTC by kovansky

Dodaje dwa pliki z akcjami, testy i push.
Co trzeba uzupełnić, żeby wszystko działało:

- `redirects-push.yml`:
  - `AZURE_FUNCTIONAPP_NAME` (env) — nazwa Azure Function na który ma być deployowana aplikacja
  - `AZURE_FUNCTIONAPP_PUBLISH_PROFILE` (secret) — profil publikacji z Azure (opisane w README)
- `redirects-test.yml`:
  - `AZURE_SUBSCRIPTION_ID` (env) — ID subskrypcji na Azure
  - `AZURE_RESOURCE_GROUP` (env) — nazwa odpowiedniej Resource Grupy
  - `AZURE_CREDENTIALS` (secret) — credentialsy do logowania na Azure do odpowiedniej subskrypcji z dostępem do powyższej Resource Grupy.

2021-05-31 13:36 UTC, szczot3k commented on .github/workflows/redirects-test.yml
> +    push:
czemu test redirects odpalać ma się przy pushu?

2021-05-31 13:36 UTC, szczot3k commented on .github/workflows/redirects-test.yml
> +    pull_request:
`pull_request` nie jest forko-odporne - w tym przypadku trzeba użyć `pull_request_target`

2021-05-31 14:08 UTC, kovansky commented on .github/workflows/redirects-test.yml
> +    push:
Potrzebowałem do testu — zapomniałem usunąć

2021-05-31 14:08 UTC, kovansky commented on .github/workflows/redirects-test.yml
> +    pull_request:
Już zmieniam

2021-05-31 14:14 UTC, kovansky commented on .github/workflows/redirects-test.yml
> +    pull_request:
Jeżeli dobrze rozumiem, to to zmienia działanie w taki sposób, że akcja zamiast w repo głównym odpala się na forku? Czy co to dokładnie daje?

2021-05-31 14:38 UTC, szczot3k commented on .github/workflows/redirects-test.yml
> +    pull_request:
Spojrzałem jeszcze raz. Czy będziemy wrzucali gdziekolwiek w te workflow'y jakiekolwiek secrety?

2021-05-31 15:15 UTC, kovansky commented on .github/workflows/redirects-test.yml
> +    pull_request:
Są dwa, credentialsy używane przy validatowania pliku ARM (w testach) i publish profile używany do pushowania apki do Azure (w pushu)

2021-06-01 05:43 UTC, karol-gro requested changes

2021-06-01 05:43 UTC, karol-gro commented on .github/workflows/redirects-push.yml
> +            -   name: Deploy
Czemu nie deploy'ujemy tu ARMa?

2021-06-01 05:43 UTC, karol-gro commented on .github/workflows/redirects-push.yml
> +                    publish-profile: ${{secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE}}
Będziemy to robić przez azure login raczej, ale to ustawię

2021-06-01 05:43 UTC, karol-gro commented on .github/workflows/redirects-push.yml
> +                working-directory: ./domains/redirects
Może możemy założyć, że testy na mainie już powinny przejść, skoro przeszły na PR? Niby zawsze można puścić, ale cały job z instalacją node'a itp. można by wywalić...

2021-06-01 05:43 UTC, karol-gro commented on .github/workflows/redirects-test.yml
> +                    template: ./domains/redirects/redirects.arm.json
Można puścić te 2 zadania w jednym jobie?

2021-06-01 05:50 UTC, karol-gro requested changes

2021-06-01 05:50 UTC, karol-gro commented on .github/workflows/redirects-test.yml
> +    pull_request_target:
to nie pójdzie na `pull_request_target`, bo używa kodu, a dostanie kod z brancha docelowego, nie źródłowego. Aby działało na merge lokalny potrzebujesz `pull_request`, a jeśli ma działać też test ARMa pomiędzy repozytoriami to potrzedujesz `pull_request` puszczajacy testy node'a i emitujący ARM w artefakcie oraz `workflow_run` pobierający ten ARM i walidujący go z Azurem

2021-06-01 05:50 UTC, karol-gro commented on .github/workflows/redirects-test.yml
> +    pull_request:
pull_request_target nie przetestuje nowego kodu, napisałem to w osobnym komentarzu

2021-06-01 11:44 UTC, kovansky commented on .github/workflows/redirects-push.yml
> +            -   name: Deploy
Przez to, co pisałem na Teamsach — jeśli dobrze mi się wydaje, to nadpisywałoby ustawienia co do custom domeny (*.zhp.net.pl) i prawdopodobnie wymagałoby przy każdym deployu walidacji domeny, czyli istnienia rekordu CNAME wildcardowego, czego chcieliśmy uniknąć

2021-06-01 11:45 UTC, kovansky commented on .github/workflows/redirects-test.yml
> +                    template: ./domains/redirects/redirects.arm.json
A można

2021-06-01 11:48 UTC, kovansky commented on .github/workflows/redirects-test.yml
> +    pull_request_target:
Chyba nie rozumiem, szczerze mówiąc 😅 ale w takim razie jednak mam zmienić na `pull_request`?

2021-06-01 13:08 UTC, szczot3k commented on .github/workflows/redirects-test.yml
> +    pull_request_target:
Github Actions jest jednak bardziej skomplikowane, jeżeli chodzi o secrets. 
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

2021-06-01 17:03 UTC, karol-gro commented on .github/workflows/redirects-test.yml
> +    pull_request_target:
Na razie dałem `pull_request`, z forka commit się wywali, ale to do poprawienia (może być później)

2021-06-01 17:07 UTC, karol-gro commented on .github/workflows/redirects-push.yml
> +            -   name: Deploy
Zróbmy tak: na razie to dodamy i sprawdzimy. Jak wywali nam przypisane domeny to się ogarnie. Ale ARM nie powinien tego robić (w pracy wrzucam tak CDN-y i domeny im zostają)

2021-06-01 17:09 UTC, karol-gro approved these changes
Na razie OK. Trzeba zobaczyć, czy nie usunie tych domen oraz coś zrobić z merge'ami z forków, ale na razie można IMHO już wrzucić

2021-06-01 19:21 UTC, merged