initial cleanup lodzka
itwzhp/infrastruktura pull request #90
Opened 2021-09-03 17:14 UTC by czytacz

domeny związane z Łódzką przeniesione do osobnego pliku

2021-09-04 18:00 UTC, czytacz commented
Dodano zmianę związaną z migracją strona Piotrkowa na hosting ChŁ

2021-09-06 08:54 UTC, karol-gro requested changes
Zostawiam kilka uwag

2021-09-06 08:54 UTC, karol-gro commented on domains/zhp.pl.d/lodzka.js
> +    CNAME('www.lowicz', 'lowicz.zhp.pl.'),
Te 2 wpisy najlepiej by było załatwić przez `Delegation_A('lowicz', '85.128.206.44'),`

2021-09-06 08:54 UTC, karol-gro commented on domains/zhp.pl.d/lodzka.js
> +    MX('lowicz', 10, 'lowicz.zhp.pl.'),
Tam serio są jakieś skrzynki czy to copy-paste skądś tam?

2021-09-06 08:54 UTC, karol-gro commented on domains/zhp.pl.d/lodzka.js
> +    A('pabianice', '79.133.210.186'),
`Delegation_A` - obsłuży też www

2021-09-06 08:54 UTC, karol-gro commented on domains/zhp.pl.d/lodzka.js
> +    TXT('pabianice', 'v=spf1 include:spf.protection.outlook.com -all'),
`Ms365_Subdomain` - brakuje kilku ustawień dla MS, to załatwi wszystko

2021-09-06 08:54 UTC, karol-gro commented on domains/zhp.pl.d/lodzka.js
> +    CNAME('*.wypoczynek.lodzka', 'wypoczynek.lodzka.zhp.pl.'),
Czy serio macie tam coś pod * innego niż www?
BTW, tam nic nie ma poza "domena na atthost"

2021-09-06 08:54 UTC, karol-gro commented on domains/zhp.pl.d/lodzka.js
> +    MX('wypoczynek.lodzka', 10, 'wypoczynek.lodzka.zhp.pl.'),
macie tam jakąś pocztę? Podejrzewam, że to naszłość

2021-09-06 08:54 UTC, karol-gro commented on domains/zhp.pl.d/lodzka.js
> +    MX('ratownicy.lodzka', 10, 'ratownicy.lodzka.zhp.pl.'),
Jak wyżej - pewnie niepotrzebna * oraz MX. No i też tam nic nie widzę

2021-09-06 08:54 UTC, karol-gro commented on domains/zhp.pl.d/lodzka.js
> +    MX('swieto2011.lodzka', 10, 'swieto2011.lodzka.zhp.pl.')
Podejrzewam, że 10 lat to tam nie świętujecie ;)

2021-09-06 11:05 UTC, czytacz commented on domains/zhp.pl.d/lodzka.js
> +    MX('lowicz', 10, 'lowicz.zhp.pl.'),
Wpisuję sobie w todo, po weryfikacji ew. stworzę nowego PR który to wyczyści

2021-09-06 11:06 UTC, czytacz commented on domains/zhp.pl.d/lodzka.js
> +    TXT('pabianice', 'v=spf1 include:spf.protection.outlook.com -all'),
done

2021-09-06 11:06 UTC, czytacz commented on domains/zhp.pl.d/lodzka.js
> +    CNAME('*.wypoczynek.lodzka', 'wypoczynek.lodzka.zhp.pl.'),
zweryfikowane i wyczyszczone

2021-09-06 11:06 UTC, czytacz commented on domains/zhp.pl.d/lodzka.js
> +    A('pabianice', '79.133.210.186'),
poprawione

2021-09-06 11:07 UTC, czytacz commented on domains/zhp.pl.d/lodzka.js
> +    MX('wypoczynek.lodzka', 10, 'wypoczynek.lodzka.zhp.pl.'),
zweryfikowane i wyczyszczone

2021-09-06 11:07 UTC, czytacz commented on domains/zhp.pl.d/lodzka.js
> +    MX('ratownicy.lodzka', 10, 'ratownicy.lodzka.zhp.pl.'),
zweryfikowane i wyczyszczone

2021-09-06 11:07 UTC, czytacz commented on domains/zhp.pl.d/lodzka.js
> +    MX('swieto2011.lodzka', 10, 'swieto2011.lodzka.zhp.pl.')
zweryfikowane i wyczyszczone

2021-09-06 11:08 UTC, czytacz commented on domains/zhp.pl.d/lodzka.js
> +    CNAME('www.lowicz', 'lowicz.zhp.pl.'),
done

2021-09-06 11:09 UTC, czytacz commented
Uwagi uwzględnione, poprawka wrzucona na repo

2021-09-06 13:25 UTC, karol-gro approved these changes

2021-09-06 13:26 UTC, merged